version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courses
    ports:
      - "3306:3306"
