version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
    ports:
      - "3306:3306"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    restart: always
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  migrate:
    image: migrate/migrate
    depends_on:
      - mysql
    volumes:
      - ./sql/migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "mysql://root:root@tcp(mysql:3306)/orders",
      "up"
    ]
    restart: on-failure

  goapp:
    restart: always
    build: .
    container_name: orders-app
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - "8000:8000"
      - "50051:50051"
      - "8080:8080"
