name: goexpert-labs
version: '3.8'
services:
  devcontainer:
    container_name: goexpert-labs-devcontainer
    image: mcr.microsoft.com/devcontainers/base:bullseye
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
