name: goexpert-labs
version: '3.8'
services:
  devcontainer:
    container_name: goexpert-labs-devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  gophernotes:
    image: gopherdata/gophernotes:latest-ds
    container_name: goexpert-labs-gophernotes
    ports:
      - "8888:8888"
    volumes:
      - ../..:/workspaces:cached
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser --NotebookApp.token='.' --NotebookApp.password=''
