name: goexpert-labs
version: '3.8'
services:
  devcontainer:
    container_name: goexpert-labs-devcontainer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
