// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Category struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description,omitempty"`
	Courses     []*Course `json:"courses"`
}
	
type CategoryInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type Course struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description *string   `json:"description,omitempty"`
	Category    *Category `json:"category"`
}

type CourseInput struct {
	Title       string  `json:"title"`
	Description *string `json:"description,omitempty"`
	CategoryID  string  `json:"categoryId"`
}

type Mutation struct {
}

type Query struct {
}
